apps/news/urls.py
from django.urls import path
from . import views
app_name='news'
urlpatterns = [
    #path('',views.index,name="index"),
    path('<int:news_id>', views.news_detail, name="news_detail"),
    path('list/',views.news_list,name='news_list'),
    # path('sidebar/',views.sidebar,name='siderbar'),
    path('public_comment/',views.public_comment,name='public_comment'),
    path('search/', views.search, name="search"),
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('news/',include('apps.news.urls')),
    path('cms/',include('apps.cms.urls')),
    path('account/',include('apps.xfzauth.urls')),
    path('course/',include("apps.course.urls")),
    path('payinfo/',include("apps.payinfo.urls")),
    path('ueditor/',include('apps.ueditor.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/news/models.py
from django.db import models

# Create your models here.
class NewsCategory(models.Model):
    name=models.CharField(max_length=100)

class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory',on_delete=models.SET_NULL,null=True)
    author = models.ForeignKey('xfzauth.User',on_delete=models.SET_NULL,null=True)

    class Meta:
        ordering = ['-pub_time']

class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News",on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey("xfzauth.User",on_delete=models.CASCADE)

    class Meta:
        ordering = ['-pub_time']

class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-priority']

apps/news/forms.py
from django import forms
from apps.forms import FormMixin
from .models import Banner

class PublicCommentForm(forms.Form,FormMixin):
    content = forms.CharField()
    news_id = forms.IntegerField()

apps/news/views.py
from django.shortcuts import render
from .models import News,NewsCategory,Comment,Banner
from django.conf import settings
from .serializers import NewsSerializer,CommentSerizlizer
from django.http import Http404
from utils import restful
from .forms import PublicCommentForm
from apps.xfzauth.decorators import xfz_login_required
from django.db.models import Count

# Create your views here.
def index(request):
    count=settings.ONE_PAGE_NEWS_COUNT
    newses=News.objects.order_by('-pub_time')[0:count]
    categories=NewsCategory.objects.all()
    sidebars = News.objects.order_by('-pub_time').first()
    context={
        'newses':newses,
        'categories':categories,
        'banners':Banner.objects.all(),
        'sidebars': sidebars
    }
    print(sidebars.pub_time)

    return render(request,'news/index.html',context=context)
# def sidebar(request):
#     sidebars = News.objects.order_by('-pub_time').first()
#     context={
#         'sidebars': sidebars
#     }
#     print(sidebars.pub_time)
#     return render(request,"common/sidebar.html",context=context)

def news_list(request):
    # 通过p参数，来指定要获取第几页的数据
    # 并且这个p参数，是通过查询字符串的方式传过来的/news/list/?p=2
    page = int(request.GET.get('p',1))
    # 分类为0：代表不进行任何分类，直接按照时间倒序排序
    category_id = int(request.GET.get('category_id',0))
    # 0,1
    # 2,3
    # 4,5
    start = (page-1)*settings.ONE_PAGE_NEWS_COUNT
    end = start + settings.ONE_PAGE_NEWS_COUNT

    if category_id == 0:
        # QuerySet
        # {'id':1,'title':'abc',category:{"id":1,'name':'热点'}}
        newses = News.objects.select_related('category','author').all()[start:end]
    else:
        newses = News.objects.select_related('category','author').filter(category__id=category_id)[start:end]
    serializer = NewsSerializer(newses,many=True)
    data = serializer.data
    return restful.result(data=data)


def news_detail(request,news_id):
    try:
        news = News.objects.select_related('category','author').get(pk=news_id)
        counts=News.objects.filter(pk=news_id).annotate(news_type=Count("comments"))
        context = {
            'news': news,
            'counts':counts
        }

        for count in counts:
            print(count.news_type)

        return render(request,'news/news_datail.html',context=context)
    except News.DoesNotExist:
        raise Http404
@xfz_login_required
def public_comment(request):
    form = PublicCommentForm(request.POST)
    if form.is_valid():
        news_id = form.cleaned_data.get('news_id')
        content = form.cleaned_data.get('content')
        news = News.objects.get(pk=news_id)
        comment = Comment.objects.create(content=content,news=news,author=request.user)

        serizlize = CommentSerizlizer(comment)
        return restful.result(data=serizlize.data)
    else:
        return restful.params_error(message=form.get_errors())



def search(request):
    return render(request,'search/search.html')

front/templates/news/index.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title%}新闻首页{% endblock %}
{% block head%}
    <link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/index.min.js' %}"></script>
    <script id="news-item" type="text/html">{% verbatim %}
{{ each newses news index }}
<li>
    <div class="thumbnail-group">
        <a href="/news/{{ news.id }}">
            <img src="{{ news.thumbnail }}" alt="">
        </a>
    </div>
    <div class="news-group">
        <p class="title">
            <a href="/news/{{ news.id }}">{{ news.title }}</a>
        </p>
        <p class="desc">
            {{ news.desc }}
        </p>
        <p class="more">
           <span class="category">{{ news.category.name }}</span>
            <span class="pub-time">{{ news.pub_time|timeSince }}</span>
            <span class="author">{{ news.author.username }}</span>
        </p>
    </div>
</li>
{{ /each }}
{% endverbatim %}
    </script>
{% endblock %}
{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="banner-group" id="banner-group">
                    <ul class="banner-ul" id="banner-ul">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.link_to }}">
                                    <img src="{{ banner.image_url }}" alt="">
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                    <span class="arrow left-arrow">‹</span>
                    <span class="arrow right-arrow">›</span>
                    <div class="page-control-group">
                        <ul class="page-control">
                        </ul>
                    </div>
                </div>
                <div class="list-outer-group">
                    <ul class="list-tab">
                        <li data-category="0" class="active"><a href="javascript:void(0);">最新资讯</a></li>
                        {% for category in categories %}
                            <li data-category="{{ category.pk }}"><a href="javascript:void(0);">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                    <ul class="list-inner-group">
                        {% for news in newses %}
                            <li>
                            <div class="thumbnail-group">
                                <a href="{% url 'news:news_detail' news_id=news.pk %}">
                                    <img src="{{ news.thumbnail }}" alt="">
                                </a>
                            </div>
                            <div class="news-group">
                                <p class="title">
                                    <a href="{% url 'news:news_detail' news_id=news.pk %}">{{ news.title }}</a>
                                </p>
                                <p class="desc">
                                    {{ news.desc }}
                                </p>
                                <p class="more">
                                   <span class="category">{{ news.category.name }}</span>
                                    <span class="pub-time">{{ news.pub_time|time_since }}</span>
                                    <span class="author">{{ news.author.username }}</span>
                                </p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="load-more-group">
                        <button class="load-more" id="load-more-btn">查看更多</button>
                    </div>
                </div>
            </div>
{#            {% include 'common/sidebar.html' %}#}
        <div class="sidebar-wrapper">
                <div class="title-group">
                    <span class="title">在线课堂</span>
                    <a class="more" href="#">更多</a>
                </div>
                <div class="advertise-group">
                    <a href="#">
                        <img src="http://www.xfz.cn/static/build/images/side-gift-banner.png" alt="">
                    </a>
                </div>
                <div class="platform-group">
                    <div class="title-group">
                        <span class="title">关注小饭桌</span>
                    </div>
                    <div class="focus-group">
                        <ul class="left-group">
                           <li class="zhihu">
                               <a href="#" target="_blank">小饭桌创业课堂</a>
                           </li>
                            <li class="weibo">
                               <a href="#" target="_blank">小饭桌创业课堂</a>
                           </li>
                            <li class="toutiao">
                               <a href="#" target="_blank">小饭桌</a>
                           </li>
                        </ul>
                        <div class="right-group">
                            <p class="desc">扫码关注小饭桌微信公众平台xfz008</p>
                        </div>
                    </div>
                </div>
                <div class="hot-news-group">
                    <div class="title-group">
                        <span class="title">热门推荐</span>
                    </div>
                    <ul class="hot-list-group">
                        <li>
                            <div class="left-group">
                                <p class="title" style="font-size: 15px">
                                    <a href="{% url 'news:news_detail' news_id=sidebars.pk %}">{{ sidebars.title }}</a>
                                </p>
                                <p class="more">

                                    <span class="category">{{ sidebars.desc }}</span>

                                    <span class="pub-time">{{ sidebars.pub_time|time_since }}</span>
                                </p>
                            </div>
                            <div class="right-group">
                                <a href="{% url 'news:news_detail' news_id=sidebars.pk %} ">
                                    <img src="{{ sidebars.thumbnail }}" alt="">
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/news/news_datail.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title%}新闻详情{% endblock %}
{% block head%}
    <link rel="stylesheet" href="{% static 'css/news/news_datail.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/news_detail.min.js' %}"></script>
    <script id="comment-item" type="text/html">
{% verbatim %}
<li>
    <div class="comment-info">
        <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
        <span class="author">{{ comment.author.username }}</span>
        <span class="pub-time">{{ comment.pub_time|timeSince }}</span>
    </div>
    <p class="comment-content">{{ comment.content }}</p>
</li>
{% endverbatim %}
</script>
{% endblock %}
{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="news-wrapper">
                    <h1 class="title">{{ news.title }}</h1>
                    <div class="news-info">
                        <div class="info-group">
                            <span class="author">{{ news.author.username }}</span>
                            <span class="pub-time">{{ news.pub_time|time_since }}</span>
                            <span class="category">{{ news.category.name }}</span>
                        </div>
                        <div class="share-group">
                            <span>分享至：</span>
                            <a class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                    </div>
                    <article class="article">
					{{ news.content|safe }}
                    </article>
                </div>
                <div class="comment-wrapper">
                    {% for count in counts %}
                    <h3 class="title" >文章评论({{ count.news_type }})</h3>
                {% endfor %}
                    <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
                    <div class="submit-btn-group">
                        <button class="submit-btn" data-news-id="{{ news.pk }}">立即评论</button>
                    </div>
                    <ul class="comment-list">
                        {% for comment in news.comments.all %}
                            <li>
                                <div class="comment-info">
                                    <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
                                    <span class="author">{{ comment.author.username }}</span>
                                    <span class="pub-time">{{ comment.pub_time|time_since }}</span>
                                </div>
                                <p class="comment-content">{{ comment.content }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}